### ISSUE TITLE
Problems installing on Mac OS

### ISSUE THREAD

**Issue by TomSemblanet** [bradbell/cppad_py#11]
I have so problem while building the 'cppad_py/_cppad_swig' extension.
When I enter the command `python setup.py build_ext`, I've got the followig error : 

`MACOSX_RPATH is not specified for the following targets:`
`_cppad_swig`

How can I solve it ?

Thank you.

**Comment by bradbell** [comment]
It seems from the comment above that you are installing cppad_py on a Mac ?

**Comment by TomSemblanet** [comment]
I'm on a Mac, yes

**Comment by TomSemblanet** [comment]
Sorry, the full warning is : 

`CMake Warning (dev):`
 `Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake`
  `--help-policy CMP0042" for policy details.  Use the cmake_policy command to`
  `set the policy and suppress this warning.`

`  MACOSX_RPATH is not specified for the following targets:`

 ` _cppad_swig`

`This warning is for project developers.`

**Comment by bradbell** [comment]
I have just installed a mac virtual machine for testing.
I am following the steps in
https://bradbell.github.io/cppad_py/doc/xsrst/setup_py.html#setup-py-test-build-cppad-py

I had to change my python using
https://opensource.com/article/19/5/python-3-default-mac
to get `python3 setup.py build_ext` to work.

**Comment by TomSemblanet** [comment]
I have Python 3.8.3 and followed the steps on https://bradbell.github.io/cppad_py/doc/xsrst/setup_py.html#setup-py-test-build-cppad-py but still got the linkage problem.

I find the error further :  when I launch `python example/python/check_all.py`, I have the error `ModuleNotFoundError: No module named '_cppad_swig'`

Everything went well on your virtual machine ?

**Comment by bradbell** [comment]
I got the following response at the end of `brew install numpy`:
```
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

python@3.9 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have python@3.9 first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@3.9/bin:$PATH"' >> ~/.zshrc

For compilers to find python@3.9 you may need to set:
  export LDFLAGS="-L/usr/local/opt/python@3.9/lib"

```

**Comment by TomSemblanet** [comment]
Ok ... still don't see where the problem could come from :(

**Comment by bradbell** [comment]
I executed the two suggested exports above and now am now getting your error; i.e., I have reproduced your problem. I need to go now, but will get back to this later today. Thanks
```
bradbell@Brads-iMac cppad_py.git % python3 example/python/check_all.py
Traceback (most recent call last):
  File "/Users/bradbell/repo/cppad_py.git/example/python/check_all.py", line 76, in <module>
    ok = run_test(name, name)
  File "/Users/bradbell/repo/cppad_py.git/example/python/check_all.py", line 20, in run_test
    exec( 'ok = '   + module_name + '.' + fun_name + '()', namespace )
  File "<string>", line 1, in <module>
  File "./a_double_cond_assign_xam.py", line 14, in a_double_cond_assign_xam
    import cppad_py
  File "/Users/bradbell/repo/cppad_py.git/cppad_py/__init__.py", line 13, in <module>
    from cppad_py.cppad_swig import abort_recording
  File "/Users/bradbell/repo/cppad_py.git/cppad_py/cppad_swig.py", line 13, in <module>
    from . import _cppad_swig
ImportError: cannot import name '_cppad_swig' from partially initialized module 'cppad_py' (most likely due to a circular import) (/Users/bradbell/repo/cppad_py.git/cppad_py/__init__.py)
bradbell@Brads-iMac cppad_py.git % 
```

**Comment by TomSemblanet** [comment]
Thank you very much !

**Comment by bradbell** [comment]
I have the library loading locally now (with the current master for cppad_py).
After executing `bin/get_cppad.sh`, the following script works (please try it)
```
rm -r build
rm -rf build.debug
rm -rf build.release
python3 setup.py build_ext --inplace
export DYLD_LIBRARY_PATH="$HOME/prefix/cppad/lib"
dir=$(find -L build -name 'lib.macosx-*')
cd "$dir"
cat << EOF > check.py
import sys
sys.path.insert(0, '.')
import cppad_py
print('import cppad_py: OK')
sys.exit(0)
EOF
python3 check.py
echo 'check.sh: OK'
exit 0
```

**Comment by bradbell** [comment]
The following script runs, but if you remove the comment infront of the make command at the end it fails:
```
#! /bin/bash -e
rm -rf build
rm -rf build.debug
rm -rf build.release
export DYLD_LIBRARY_PATH="$HOME/prefix/cppad/lib"
bin/build_local.py
cd build
make example_cplusplus_check_all
cd example/cplusplus
./example_cplusplus_check_all
# The commented out make command below runs ./example/cplusplus_check_all.
# I think it fails because DYLD_LIBRARY_PATH is not being exported to make.
# make check_example_cplusplus
echo 'check.sh: OK'
exit 0
```

**Comment by TomSemblanet** [comment]
Hi, thank for your help. 
Indeed, the last script - launched after bin/get_cppad.sh - runs well. 

However, I still have the error `ModuleNotFoundError: No module named '_cppad_swig'` when I try to import cppad_py in a Python script.

While running the script above, I have the following logs : 
![Capture d’écran 2020-10-28 à 22 01 33](https://user-images.githubusercontent.com/62354610/97496470-454f0880-1969-11eb-962f-27701ebe808f.png)
![Capture d’écran 2020-10-28 à 22 02 01](https://user-images.githubusercontent.com/62354610/97496474-4718cc00-1969-11eb-99de-e20c81b0993d.png)

Then, 
![Capture d’écran 2020-10-28 à 22 04 15](https://user-images.githubusercontent.com/62354610/97496641-89420d80-1969-11eb-9f76-7e8d2af1c85b.png)

I must surely miss something.

**Comment by bradbell** [comment]
If you are still getting the policy error then I suspect that you need to do
```
git reset --hard
git pull
```
Does the first script (the one with check.py) work for you after the commands above ?

OK. you can try it now.

**Comment by bradbell** [comment]
The following script imports the installed version of cppad_py, but it does it by changing into the installation directory, not by using PYTHONPATH:
```
! /bin/bash -e
echo_eval() {
    echo $*
    eval $*
}
rm -rf build
rm -rf build.debug
rm -rf build.release
prefix="$HOME/prefix/cppad"
export DYLD_LIBRARY_PATH="$prefix/lib"
echo_eval python3 setup.py install --prefix=$prefix
dir=$(find -L $prefix -name 'cppad_py-*.egg')
echo_eval cd $dir
#
cat << EOF > check.py
import sys
sys.path.insert(0, '.')
import cppad_py
print('import cppad_py: OK')
sys.exit(0)
EOF
echo_eval python3 check.py
echo 'check.sh: OK'
exit 0
```

**Comment by TomSemblanet** [comment]
Still the same error ...

![Capture d’écran 2020-10-29 à 10 07 26](https://user-images.githubusercontent.com/62354610/97547800-904f3700-19ce-11eb-9f06-11c6c4f1e1fe.png)

**Comment by TomSemblanet** [comment]
Log obtained at the end of the script

**Comment by TomSemblanet** [comment]
What I do is : 

1. Cloning cppad_py from git
2. In get_cppad.sh, I modify cppad_prefix='/opt/anaconda3/cppad'
3. Launch the shell get_cppad.sh
4. I run the script you gave me in your last message

I am missing something ? 

Note : I have to put the variable _cxx_has_stdlib_ to False manually in setup.py. If not, I have the following logs during the execution of setup.py : 

![Capture d’écran 2020-10-29 à 10 12 15](https://user-images.githubusercontent.com/62354610/97548295-3b5ff080-19cf-11eb-95fe-964d53074fb8.png)

**Comment by bradbell** [comment]
Try the following:
```
bin/build_local.py > build_local.out
grep 'CXX' build_local.out
grep 'cxx_has_stdlib' build_local.out
```
To determine which compiler CMake is detecting and if it is detecting stdlib.

**Comment by TomSemblanet** [comment]
I have the following logs. Is the _skipped_ check for working CXX compiler normal ?

![Capture d’écran 2020-10-29 à 13 59 54](https://user-images.githubusercontent.com/62354610/97576944-0cf20d80-19ef-11eb-9b5d-b931a574bffb.png)

**Comment by bradbell** [comment]
So this is interesting, cmake is preferring clang while setup.py if perferring gcc. I think I can fix that and will get back to you when I do.

**Comment by bradbell** [comment]
@TomSemblanet Please run the following script (it is now working on my mac system). Note there is no local cppad_py directory during this test so the installed directory is being used.  

1. You need to do a pull of the current cppad_py master.

2. python3.9 (in the script below) will need to be changed to the version of python on your system.

3. The Mac requires cppad_libdir in `bin/get_cppad.sh` to be changed from `lib64` to `lib`

```
! /bin/bash -e
# bash file to be sourced to do setup
echo_eval() {
    echo $*
    eval $*
}
prefix="$HOME/prefix/cppad"
export DYLD_LIBRARY_PATH="$prefix/lib"
export PYTHONPATH="$prefix/lib/python3.9/site-packages"
#
prefix="$HOME/prefix/cppad"
echo_eval rm -r  $prefix
#
echo_eval rm -rf build
echo_eval rm -rf build.debug
echo_eval rm -rf build.release
echo_eval rm -rf cppad_py
#
echo "bin/get_cppad.sh >& get_cppad.log"
bin/get_cppad.sh >& get_cppad.log
#
echo "python3 setup.py install --prefix=$prefix >& setup.log"
python3 setup.py install --prefix=$prefix >& setup.log
#
cat << EOF > check.py
import sys
import cppad_py
print('import cppad_py: OK')
sys.exit(0)
EOF
#
echo_eval python3 check.py
#
echo 'check.sh: OK'
exit 0
```

**Comment by TomSemblanet** [comment]
Hi, 

I tried the last script but it doesn't seem to work for me. I'll come back to this problem in some days I've some work waiting.
Thank you very much for your help !

**Comment by TomSemblanet** [comment]
I've seen that the installation on macOS is now automatic. 
`ModuleNotFoundError: No module named '_swig'` still persists.

I read that ModuleNotFoundError are raised in one of the 3 following cases : 

1. The name of the module is incorrect
2. The path of the module is incorrect
3. The library isn't installed

However, Swig is well installed on my computer, `which swig` returns `/opt/anaconda3/bin/swig`

**Comment by TomSemblanet** [comment]
Maybe the logs could help ... 

![Capture d’écran 2020-11-05 à 16 14 44](https://user-images.githubusercontent.com/62354610/98259276-34625080-1f82-11eb-8e5a-1a1fcc24b17d.png)

**Comment by bradbell** [comment]
Please re-test this, with the current version, and report back what happens.
Thanks.
